#!/bin/bash

set -ex

cd $(dirname $0)

source config
./scripts/brew
./scripts/node
./scripts/python
./scripts/ruby
./scripts/haskell
./scripts/go
./scripts/rust
./scripts/vim
./scripts/etc
./scripts/macos
