#!/bin/bash

set -e

# Install Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install packages from Homebrew
brew update
brew upgrade

brew install \
	ctags \
	git \
	neovim \
	zsh \
	zsh-syntax-highlighting \
	pyenv \
	pyenv-virtualenv \
	rbenv

brew install yarn --ignore-dependencies

# Cask
brew tap homebrew/cask
brew cask install \
	1password \
	atom \
	discord \
	docker \
	gimp \
	gitkraken \
	google-chrome \
	google-japanese-ime \
	hyperswitch \
	insomnia \
	iterm2 \
	kap \
	karabiner-elements \
	obs \
	postico \
	slack \
	spotify \
	visual-studio-code \
	firefox \
	google-backup-and-sync

brew cleanup
