#!/bin/bash

set -eu

curl -L https://git.io/n-install | bash

n ${NODE_VERSION}

npm install --global \
	@hoishin/editorconfig \
	fkill-cli \
	internal-ip-cli\
	neovim \
	np \
	onchange \
	public-ip-cli \
	pure-prompt \
	sort-package-json \
	trash-cli \
	trymodule \
	ts-node \
	typescript
