#!/bin/bash

set -eu

curl -fsL https://github.com/creationix/nvm/raw/master/install.sh | bash
source $HOME/.nvm/nvm.sh

nvm install 10

npm install --global pure-prompt

yarn global add \
	@nestjs/cli \
	@vue/cli \
	apidoc \
	bower \
	browserslist \
	clipboard-cli \
	del-cli \
	dts-gen \
	esdoc \
	eslint \
	find-process \
	fkill-cli \
	generator-nm \
	get-port-cli \
	http-server \
	internal-ip-cli \
	javascript-typescript-langserver \
	jsdoc \
	lock-cli \
	make-dir-cli \
	neovim \
	node-notifier-cli \
	nodecg-cli \
	np \
	onchange \
	pg-stored-procedure \
	pm2 \
	prettier \
	public-ip-cli \
	release-it \
	serverless \
	sort-package-json \
	trash-cli \
	tree-cli \
	trymodule \
	ts-node \
	tslint \
	typed-css-modules \
	typedoc \
	typescript \
	typewiz \
	typewiz-node \
	vue-language-server \
	vuepress \
	xo \
	yo
