#!/bin/bash

set -eu

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

pyenv install ${PYTHON2_VERSION}
pyenv install ${PYTHON3_VERSION}

pyenv virtualenv ${PYTHON2_VERSION} neovim2
pyenv virtualenv ${PYTHON3_VERSION} neovim3

pyenv activate neovim2
pip install neovim

pyenv activate neovim3
pip install neovim
