#!/bin/bash

set -e

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

pyenv install 2.7.15
pyenv install 3.7.2

pyenv virtualenv 2.7.15 neovim2
pyenv virtualenv 3.7.2 neovim3

pyenv activate neovim2
pip install neovim

pyenv activate neovim3
pip install neovim
