#!/bin/bash

set -e

curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash

export PATH="~/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

pyenv install 2.7.15
pyenv install 3.7.0

pyenv virtualenv 2.7.15 neovim2
pyenv virtualenv 3.7.0 neovim3

pyenv activate neovim2
pip install neovim

pyenv activate neovim3
pip install neovim
