#!/bin/bash

set -e

curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash || true

which rbenv
rbenv install 2.5.1
rbenv global 2.5.1

gem install rsense rubocop neovim travis
